name: Test

on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  build_docker_images:
    name: Build and test docker images
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: "Build the docker-compose stack with version"
      run: docker compose -f docker/docker-compose.yml build
