name: Test

on: 
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  PYTHON_VERSION: '3.11'
  SC2_VERSION: '4.10-bookworm'

jobs:

  build_docker_images:
    name: Build and test docker images
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: "Build the docker-compose stack with version"
      run: PYTHON_VERSION="${{ env.PYTHON_VERSION }}" SC2_VERSION="${{ env.SC2_VERSION }}" docker compose -f docker/docker-compose.yml build

    - name: Push versioned images
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: BOT_VERSION="${{ env.BOT_VERSION }}" PYTHON_VERSION="${{ env.PYTHON_VERSION }}" SC2_VERSION="${{ env.SC2_VERSION }}" docker compose -f docker/docker-compose.yml push --ignore-push-failures

